# Generated by Django 4.2.1 on 2023-09-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
