# Generated by Django 4.2.6 on 2023-10-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreate',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='usercreate',
            name='is_online',
        ),
    ]
