# Generated by Django 4.2.6 on 2023-10-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_remove_usercreate_current_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.team'),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
