# Generated by Django 4.2.6 on 2023-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_usercreate_current_team_usercreate_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
