# Generated by Django 4.2.1 on 2023-09-10 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0003_userteam_alter_attachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTeam',
            new_name='UserMember',
        ),
    ]
