# Generated by Django 4.2.6 on 2023-11-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_notification_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
