# Generated by Django 4.2.6 on 2023-11-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='task_management.attachment'),
        ),
    ]
