# Generated by Django 4.2.1 on 2023-09-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_userteams_delete_usermember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTeams',
        ),
    ]
