# Generated by Django 4.2.1 on 2023-09-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_userteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='user',
        ),
    ]
