# Generated by Django 4.2.1 on 2023-09-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_userteam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='profile_picture',
        ),
    ]
