# Generated by Django 4.2.1 on 2023-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_remove_userteam_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
