# Generated by Django 4.2.1 on 2023-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0013_usercreate_delete_userteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
    ]
