# Generated by Django 4.2.1 on 2023-09-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0015_alter_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
