# Generated by Django 4.2.1 on 2023-09-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0017_remove_team_member_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreate',
            name='role',
        ),
    ]
