# Generated by Django 4.2.1 on 2023-09-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0018_remove_usercreate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
