# Generated by Django 4.2.1 on 2023-09-16 22:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_management', '0019_usercreate_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTeam',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.team')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
