# Generated by Django 4.2.1 on 2023-09-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0020_customteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
