# Generated by Django 4.2.1 on 2023-09-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0022_alter_team_options_remove_usercreate_role_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority'), ('Critical', 'Critical Priority'), ('Blocker', 'Blocker Priority')], max_length=20, unique=True)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#FFA500', 'Orange'), ('#FFFF00', 'Yellow'), ('#800000', 'Dark Red'), ('#000000', 'Black')], default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_id',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_management.priority'),
        ),
    ]
