# Generated by Django 4.2.1 on 2023-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0028_alter_teammember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_member', to='task_management.teammember'),
        ),
    ]
