# Generated by Django 4.2.1 on 2023-09-28 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0032_remove_team_team_members_team_new_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='new_members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
