# Generated by Django 4.2.1 on 2023-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0041_remove_team_members_team_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members1',
            field=models.ManyToManyField(related_name='team_member', to='task_management.teammember'),
        ),
    ]
