# Generated by Django 4.2.1 on 2023-09-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0042_remove_team_team_members_team_team_members1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members1',
        ),
    ]
