# Generated by Django 4.2.1 on 2023-09-28 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0049_team_members_teammember_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_member', through='task_management.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
