# Generated by Django 4.2.1 on 2023-09-28 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0052_team_alter_customteam_team_alter_message_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
