# Generated by Django 4.2.1 on 2023-09-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0055_alter_team_team_members'),
    ]

    operations = [
    ]
