# Generated by Django 4.2.1 on 2023-09-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0063_alter_team_members'),
    ]

    operations = [
    ]
