# Generated by Django 4.2.1 on 2023-10-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0065_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.team'),
        ),
    ]
