# Generated by Django 4.2.1 on 2023-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0066_usercreate_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='project', to='task_management.team'),
        ),
    ]
