# Generated by Django 4.2.1 on 2023-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0071_rename_project_id_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(related_name='task', to='task_management.team'),
        ),
    ]
