# Generated by Django 4.2.1 on 2023-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0072_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
