# Generated by Django 4.2.6 on 2023-10-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0076_usercreate_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreate',
            name='is_online',
        ),
    ]
